version: '3.8'

services:
  # MySQL Database Only - for use with local GUI application
  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: insurance-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: insurance_db
      MYSQL_USER: insurance_user
      MYSQL_PASSWORD: insurance123
    ports:
      - "3307:3306"  # Access from host machine
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - insurance-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mysql_data:
    driver: local

networks:
  insurance-network:
    driver: bridge
